on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      greeting:
        description: "How to greet user"
        required: true
        type: string

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic Information"
        run: |
          echo "Hello, ${{ inputs.greeting }}"
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
      - name: PWD
        run: pwd
      - name: list
        run: ls -a
      - name: path
        run: echo ${{ github.action_path }}